mxsite/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin

from mxblog.views import user, post, site
from mxblog.views.start import StartView

admin.autodiscover()

urlpatterns = patterns(
    '',
    url(r'^$', site.index, name='home'),
    url(r'^register/', user.register, name='register'),
    url(r'^login/', user.login, name='login'),
    url(r'^post/(?P<bid>\d+)/', post.post, name='post'),
    url(r'^thumbs/(?P<ctype>(support)|(oppose))/(?P<bid>\d+)/', post.thumbs),
    url(r'^archive/', post.archive, name='archive'),
    url(r'^start/', StartView.as_view(), name='start'),
    url(r'^about/', site.about, name='about'),
    url(r'^ckeditor/', include('ckeditor.urls')),
    url(r'^admin/', include(admin.site.urls)),
)

mxblog/models.py
# coding=utf-8
from datetime import datetime
import os

from ckeditor.fields import RichTextField
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager, PermissionsMixin
from django.db import models
from django.utils import timezone


class PostUserManager(BaseUserManager):

    def _create_user(self, email, password, is_staff, is_superuser, **extra_fields):
        now = timezone.now()
        if not email:
            raise ValueError('The given email must be set')
        email = self.normalize_email(email)
        user = self.model(email=email, is_staff=is_staff, is_active=True, is_superuser=is_superuser, last_login=now,create_time=now, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email=None, password=None, **extra_fields):
        return self._create_user(email, password, False, False, **extra_fields)

    def create_superuser(self, email, password, **extra_fields):
        return self._create_user(email, password, True, True, **extra_fields)


class PostUser(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField(verbose_name=u"邮件", unique=True, db_index=True)
    username = models.CharField(verbose_name=u"名字", max_length=30, db_index=True)
    avatar = models.ImageField(verbose_name=u"头像", blank=True, max_length=100, upload_to=os.path.join(os.path.dirname(__file__), '..', 'static/ufiles').replace('\\', '/'))
    mobile = models.CharField(verbose_name=u"手机", max_length=11, blank=True)
    site = models.URLField(verbose_name=u"网站", max_length=255, blank=True)
    bio = models.URLField(verbose_name=u"签名", max_length=255, blank=True)
    login_count = models.IntegerField(verbose_name=u"登录次数", default=0)
    last_ip = models.CharField(verbose_name=u"最后登录IP", max_length=32, blank=True)
    birthday = models.DateField(verbose_name=u"生日", blank=True, default='1900-01-01')
    is_staff = models.BooleanField(verbose_name=u"后台权限", default=False)
    is_active = models.BooleanField(verbose_name=u"是否启用", default=True)
    update_time = models.DateTimeField(verbose_name=u"更新时间", default=datetime.now)
    create_time = models.DateTimeField(verbose_name=u"创建时间", default=datetime.now)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username']

    objects = PostUserManager()

    def get_full_name(self):
        return '%s(%s)' % (self.email, self.username)

    def get_short_name(self):
        return self.email

    def __unicode__(self):
        return self.email

    class Meta:
        db_table = 'mx_user'
        ordering = ['-update_time']
        verbose_name = u'用户'
        verbose_name_plural = u'用户'


class ModelMeta(models.Model):
    update_time = models.DateTimeField(verbose_name=u"更新时间", default=datetime.now)
    create_time = models.DateTimeField(verbose_name=u"创建时间", default=datetime.now)

    class Meta:
        abstract = True
        ordering = ['-create_time']


class PostMeta(ModelMeta):
    title = models.CharField(verbose_name=u"名称", max_length=200)
    author = models.ForeignKey(PostUser, verbose_name=u"作者", blank=True)
    type = models.IntegerField(verbose_name=u"类型", max_length=1)

    def __unicode__(self):
        return self.title

    class Meta(ModelMeta.Meta):
        db_table = 'mx_post_meta'
        verbose_name = u'属性名称'
        verbose_name_plural = u'属性名称'


class Post(ModelMeta):
    title = models.CharField(verbose_name=u"主题", max_length=100)
    content = RichTextField(verbose_name=u"内容")
    author = models.ForeignKey(PostUser, verbose_name=u"作者", blank=True)
    support = models.BigIntegerField(verbose_name=u"支持", default=0)
    oppose = models.BigIntegerField(verbose_name=u"反对", default=0)

    def __unicode__(self):
        return self.title

    class Meta(ModelMeta.Meta):
        db_table = 'mx_post'
        verbose_name = u'发布'
        verbose_name_plural = u'发布'


class PostMetaInfo(ModelMeta):
    post = models.ForeignKey(Post, verbose_name=u"主题")
    meta = models.ForeignKey(PostMeta, verbose_name=u"属性")

    def __unicode__(self):
        return self.post

    class Meta(ModelMeta.Meta):
        db_table = 'mx_post_meta_info'
        verbose_name = u'分组/标注'
        verbose_name_plural = u'分组/标注'


class Comments(ModelMeta):
    parent = models.IntegerField(verbose_name=u"上级", blank=True)
    post = models.ForeignKey(Post, verbose_name=u"主题",  blank=True)
    author = models.ForeignKey(PostUser, verbose_name=u"作者", blank=True)
    content = models.CharField(verbose_name=u"内容", max_length=1000)
    ip = models.GenericIPAddressField(verbose_name=u"IP", max_length=100)

    def __unicode__(self):
        return self.content

    class Meta(ModelMeta.Meta):
        db_table = 'mx_comments'
        verbose_name = u'留言'
        verbose_name_plural = u'留言'


class LinkGroup(ModelMeta):
    title = models.CharField(verbose_name=u"名称", max_length=100)
    author = models.ForeignKey(PostUser, verbose_name=u"作者",  blank=True)
    sort = models.IntegerField(verbose_name=u"排序", default=0, blank=False)

    def __unicode__(self):
        return self.title

    class Meta(ModelMeta.Meta):
        db_table = 'mx_link_group'
        verbose_name = u'链接分组'
        verbose_name_plural = u'链接分组'


class Links(ModelMeta):
    url = models.URLField(verbose_name=u"URL", max_length=100)
    title = models.CharField(verbose_name=u"名称", max_length=30)
    image = models.ImageField(verbose_name=u"图片", blank=True)
    description = models.CharField(verbose_name=u"简介", max_length=1000)
    owner = models.CharField(verbose_name=u"主人", max_length=1000)
    rating = models.IntegerField(verbose_name=u"评分", default=0)
    group = models.ForeignKey(LinkGroup, verbose_name=u"分组", blank=True)
    visible = models.BooleanField(verbose_name=u"显示", default=True)
    highlight = models.BooleanField(verbose_name=u"高亮", default=False)
    sort = models.IntegerField(verbose_name=u"排序", default=0, blank=False)

    def __unicode__(self):
        return self.title

    class Meta(ModelMeta.Meta):
        db_table = 'mx_links'
        verbose_name = u'链接'
        verbose_name_plural = u'链接'


class Config(ModelMeta):
    info_title = models.CharField(verbose_name=u"名称", max_length=100)
    info_key = models.CharField(verbose_name=u"键", max_length=30)
    info_value = models.CharField(verbose_name=u"值", max_length=1000)

    def __unicode__(self):
        return self.info_title

    class Meta(ModelMeta.Meta):
        db_table = 'mx_config'
        verbose_name = u'设置'
        verbose_name_plural = u'设置'

mxblog/views/post.py
import json

from django.db.models import F
from django.http import HttpResponse
from django.template.response import TemplateResponse
from mxblog.models import Post


__author__ = 'MengHX'


def post(request, bid=0):
    post = Post.objects.get(id=bid)
    return TemplateResponse(request, 'post.html', {"post": post})


def archive(request):
    postList = Post.objects.all()
    return TemplateResponse(request, 'archive.html', {"postList": postList})


def thumbs(request, ctype, bid):
    if ctype == 'support':
        Post.objects.filter(id=bid).update(support=F('support') + 1)
    elif ctype == 'oppose':
        Post.objects.filter(id=bid).update(oppose=F('oppose') + 1)

    dict = {'result': 'success'}
    return HttpResponse(json.dumps(dict), mimetype='application/json')

mxblog/views/start.py
from django.views.generic import TemplateView
from mxblog.models import LinkGroup

__author__ = 'MengHX'


class StartView(TemplateView):

    template_name = "start.html"

    def get_context_data(self, **kwargs):
        context = super(StartView, self).get_context_data(**kwargs)
        context['linkGroups'] = LinkGroup.objects.order_by('sort')
        return context

templates/about.html
{% extends 'frame/layout.html' %}
{% load staticfiles %}
{% block title %} MengHX Blog About Me {% endblock %}
{% block content %}
    <div class="container">
        <div class="row padding-large">
            <div class="col-lg-offset-0">
                <h1>STAY HUNGRY STAY FOOLISH</h1>
                <hr/>
                <p>

                <div id="wb_follow_btn"></div>
                </p>
                <script src="http://tjs.sjs.sinajs.cn/open/api/js/wb.js?appkey=1189561973" type="text/javascript"
                        charset="utf-8"></script>
                <script>
                    WB2.anyWhere(function (W) {
                        W.widget.followButton({
                            'nick_name': '_Diaoer',
                            'id': "wb_follow_btn",
                            'show_head': true,
                            'show_name': true,
                            'show_cancel': true
                        });
                    });
                </script>
                <p>Programmer@Shanghai.China</p>

                <p>Swift / Objective-C / Go / JAVA / Python ...</p>

                <p>OS X /
                    <del>Windows</del>
                    / Fedora / Ubuntu /
                    <del>Gentoo</del>
                    / Sabayon ...
                </p>
                <p><a href="https://github.com/menghx/django-blog" target="_blank">Source Code?</a></p>
            </div>
        </div>
    </div>
    </div>
{% endblock %}

templates/archive.html
{% extends 'frame/layout.html' %}
{% block title %} MengHX Blog List {% endblock %}
{% block content %}
    <ul class="list-unstyled">
        {% for cblog in postList %}
            <li>
                <div class="container well-sm">
                    <a href='{% url 'post' cblog.id %}' class="h5">{{ cblog.title }}</a>
                    <span class="pull-right">{{ cblog.create_time }}</span>
                </div>
            </li>
        {% endfor %}
    </ul>
    <ul class="pagination hidden">
        <li><a href="#">&laquo;</a></li>
        <li><a href="#">1</a></li>
        <li><a href="#">2</a></li>
        <li><a href="#">3</a></li>
        <li><a href="#">4</a></li>
        <li><a href="#">5</a></li>
        <li><a href="#">&raquo;</a></li>
    </ul>
{% endblock %}

templates/blog.html
{% extends 'frame/layout.html' %}
{% block title %} MengHX Blog {{ blog.title }} {% endblock %}
{% block content %}
    <div class="container">
        <div class="row">
            <h1>{{ blog.title }}</h1>
            <hr/>
        </div>
        <div class="row">
            {{ blog.content|safe }}
        </div>
        <div class="row">
            <br/>
            <button type="button" class="btn btn-default btn-sm">
                <span class="glyphicon glyphicon-thumbs-up"></span> {{ blog.support }}
            </button>
            <button type="button" class="btn btn-default btn-sm">
                <span class="glyphicon glyphicon-thumbs-down"></span> {{ blog.oppose }}
            </button>
            <span class="pull-right">
                        <span>{{ blog.author }}</span>
                        <span>{{ blog.create_time }}</span>
            </span>
        </div>
    </div>
{% endblock %}

templates/index.html
{% extends 'frame/layout.html' %}
{% block title %} MengHX Blog Home {% endblock %}
{% block content %}
    <div class="container">
        {% for cblog in postList %}
            <div class="row">
                <article class="well-lg">
                    <header>
                        <h3><a href='{% url 'post' cblog.id %}'>{{ cblog.title|truncatechars:30 }}</a></h3>
                        <div class="text-muted">
                            <span class="pull-right">{{ cblog.author }}&nbsp;发表于{{ cblog.create_time }}</span>
                        </div>
                        <hr/>
                    </header>
                    <div>
                        {{ cblog.content|truncatewords_html:100|safe }}
                    </div>
                    <footer>
                        <hr>
                        <button type="button" class="btn btn-default btn-sm"
                                onclick="thumbsClick(this,'{{ cblog.id }}','support')">
                            <span class="glyphicon glyphicon-thumbs-up"></span> <span>{{ cblog.support }}</span>
                        </button>
                        <button type="button" class="btn btn-default btn-sm"
                                onclick="thumbsClick(this,'{{ cblog.id }}','oppose')">
                            <span class="glyphicon glyphicon-thumbs-down"></span> <span>{{ cblog.oppose }}</span>
                        </button>
                <span class="pull-right text-primary">
                   <a class="h4" href='{% url 'post' cblog.id %}'> more...</a>
                </span>
                    </footer>
                </article>
            </div>
        {% endfor %}
    </div>
    {% if  postList.count >= 6 %}
        <a class="btn btn-default center-block" href="{% url 'archive' %}">Archives ...</a>
    {% endif %}
{% endblock %}

templates/login.html
{% extends 'frame/layout.html' %}
{% block title %} MengHX Blog User Login {% endblock %}
{% block content %}
    <div class="container" style="width: 240px; margin-top: 20px">
        <form>
            <legend>User Login</legend>
            <div class="control-group">
                <label class="control-label" for="username">Username</label>

                <div class="controls">
                    <div class="input-prepend">
                        <span class="add-on"><i class="icon-user"></i></span>
                        <input class="span2" id="username" name="username" type="text" placeholder="Type username…"/>
                    </div>
                </div>
            </div>
            <div class="control-group">
                <div class="controls">
                    <label class="control-label" for="password">Password</label>

                    <div class="input-prepend">
                        <span class="add-on"><i class="icon-lock"></i></span>
                        <input class="span2" id="password" name="password" type="password"
                               placeholder="Type password…"/>
                    </div>
                </div>
            </div>
            <div class="control-group">
                <div class="controls">
                    <label class="checkbox">
                        <input type="checkbox"> Remember me
                    </label>
                    <button type="submit" class="btn btn-primary">Login</button>
                </div>
            </div>
        </form>
    </div>
{% endblock %}

templates/post.html
{% extends 'frame/layout.html' %}
{% block title %} MengHX Blog {{ blog.title }} {% endblock %}
{% block content %}
    <div class="container">
        <div class="row">
            <h1>{{ post.title }}</h1>
            <hr/>
        </div>
        <div class="row">
            {{ post.content|safe }}
        </div>
        <div class="row">
            <br/>
            <button type="button" class="btn btn-default btn-sm">
                <span class="glyphicon glyphicon-thumbs-up"></span> {{ post.support }}
            </button>
            <button type="button" class="btn btn-default btn-sm">
                <span class="glyphicon glyphicon-thumbs-down"></span> {{ post.oppose }}
            </button>
            <span class="pull-right">
                        <span>{{ post.author }}</span>
                        <span>{{ post.create_time }}</span>
            </span>
        </div>
    </div>
{% endblock %}

templates/register.html
{% extends 'frame/layout.html' %}
{% block title %} MengHX Blog User Register {% endblock %}
{% block content %}
    <div class="container" style="width: 240px; margin-top: 20px">
        <form>
            <legend>User Register</legend>
            <div class="control-group">
                <label class="control-label" for="username">Username</label>

                <div class="controls">
                    <div class="input-prepend">
                        <span class="add-on"><i class="icon-user"></i></span>
                        <input class="span2" id="username" name="username" type="text" placeholder="Type username…"/>
                    </div>
                </div>
            </div>
            <div class="control-group">
                <div class="controls">
                    <label class="control-label" for="password">Password</label>

                    <div class="input-prepend">
                        <span class="add-on"><i class="icon-lock"></i></span>
                        <input class="span2" id="password" name="password" type="password"
                               placeholder="Type password…"/>
                    </div>
                </div>
            </div>
            <div class="control-group">
                <div class="controls">
                    <label class="control-label" for="password">Confirm Password</label>

                    <div class="input-prepend">
                        <span class="add-on"><i class="icon-lock"></i></span>
                        <input class="span2" id="repassword" name="repassword" type="password"
                               placeholder="Type Confirm password…"/>
                    </div>
                </div>
            </div>
            <div class="control-group">
                <div class="controls">
                    <button type="submit" class="btn btn-primary">Register</button>
                </div>
            </div>
        </form>
    </div>
{% endblock %}

templates/start.html
{% extends 'frame/layout.html' %}
{% load staticfiles %}
{% block custom_head %}
    {% include "start_header_extra.html" %}
{% endblock %}
{% block title %} MengHX Start Page {% endblock %}
{% block content %}
    <div id="search_content">
        <form class="search_form" id="queryForm" action="http://www.google.com/search" target="_blank">
            <input accesskey="s" id="kw" type="text" name="q" placeholder="输入关键词" onkeydown="submitForm(e)"/>
            <input class="search_btn" type="button" onclick="subForm(1)" value="Google"/>
            <input class="search_btn" type="button" onclick="subForm(2)" value="Baidu"/>
            <input class="search_btn" type="button" onclick="subForm(3)" value="Bing"/>
        </form>
    </div>
    <div class="clearfix"></div>
    <div class="link_table">
    {% for linkGroup in linkGroups %}
        <div class="link_table_row">
            <div class="link_table_row_header">
                <p>{{ linkGroup.title }}</p>
            </div>
            <ul>
                {% for link in linkGroup.links_set.all %}
                      <li><a target="_blank" title="Owner:{{ link.owner }},About:{{ link.description }}" {% if link.highlight %} class="init" {% endif %} href="{{ link.url }}">{{ link.title }}</a></li>
                {% endfor %}
            </ul>
            <div class="clearfix"></div>
        </div>
    {% endfor %}
    </div>
    <script charset="gbk" src="http://www.baidu.com/js/opensug.js"></script>
{% endblock %}

templates/start_header_extra.html
{% extends "frame/header.html" %}
{% load staticfiles %}
{% block head %}<link rel="stylesheet" href="{% static "css/start.css" %}"/>{% endblock %}